name: Ian Schechter
favicon: null
layout_spectrum: 0.7500070969108492
typography_spectrum: 0.7142702774144709
title: Ian Schechter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3847452076151967
  lightness: 0.9705045688897371
  saturation: 0.03156361682340503
  rhythmicContrast: 0.206825518514961
purpose: []
